files:
  - source: English/includes/dynamics/assets/datepicker/**/*.*
    ignore:
      - index.php
      - '*.md'
      - '*.min.js'
    translation: /%language%/includes/**/%locale%.%file_extension%
  - source: English/locale/English/**/*.*
    ignore:
      - '*.png'
      - index.php
    translation: /%language%/locale/%language%/**/%file_name%.%file_extension%
  - source: English/infusions/**/locale/English/**/*.*
    ignore:
      - index.php
    translation: /%language%/infusions/**/locale/%language%/**/%file_name%.%file_extension%
  - source: English/themes/**/*.*
    ignore:
      - index.php
    translation: /%language%/themes/**/%language%.%file_extension%
  - source: English/widgets/**/*.*
    ignore:
      - index.php
    translation: /%language%/widgets/**/%language%.%file_extension%
  - source: /English/includes/dynamics/assets/password/lang/en.js
    translation: /%language%/includes/dynamics/assets/password/lang/%two_letters_code%.%file_extension%
