tinyMCE.addI18n('nb.media_dlg',{
title:"Sett inn / rediger inkludert objekt",
general:"Generelt",
advanced:"Avansert",
file:"Fil/URL",
list:"Liste",
size:"Størrelse",
preview:"Forhåndsvisning",
constrain_proportions:"Behold størrelsesforhold",
type:"Type",
id:"Id",
name:"Navn",
class_name:"Klasse",
vspace:"Vertikal avstand",
hspace:"Horisontal avstand",
play:"Autostart",
loop:"Løkke",
menu:"Vis meny",
quality:"Kvalitet",
scale:"Skalering",
align:"Justering",
salign:"S-justering",
wmode:"W-modus",
bgcolor:"Bakgrunn",
base:"Base",
flashvars:"Flash-variabler",
liveconnect:"SWLiveConnect",
autohref:"AutoHREF",
cache:"Cache",
hidden:"Skjult",
controller:"Kontroller",
kioskmode:"Kiosk-modus",
playeveryframe:"Spill hver ramme",
targetcache:"Mål-cache",
correction:"Ingen korreksjon",
enablejavascript:"Tillat Javaskript",
starttime:"Starttid",
endtime:"Stopptid",
href:"Href",
qtsrcchokespeed:"Choke-fart",
target:"Mål",
volume:"Volum",
autostart:"Autostart",
enabled:"Kjørbar",
fullscreen:"Fullskjerm",
invokeurls:"Aktiviser URL-er",
mute:"Demp",
stretchtofit:"Strekk for å passe inn",
windowlessvideo:"Video uten vindu",
balance:"Balanse",
baseurl:"Base URL",
captioningid:"Fang opp id",
currentmarker:"Aktiv markør",
currentposition:"Aktiv posisjon",
defaultframe:"Standardramme",
playcount:"Teller",
rate:"Rate",
uimode:"UI-modus",
flash_options:"Flash-egenskaper",
qt_options:"Quicktime-innstillinger",
wmp_options:"Windows mediaplayer-innstillinger",
rmp_options:"Real mediaplayer-innstillinger",
shockwave_options:"Shockwave-innstillinger",
autogotourl:"Auto-gå-til-URL",
center:"Midtstill",
imagestatus:"Bildestatus",
maintainaspect:"Behold størrelsesforhold",
nojava:"Ikke Java",
prefetch:"Forhåndsregistrer",
shuffle:"Miks",
console:"Konsoll",
numloop:"Antall gjennomløp",
controls:"Kontroller",
scriptcallbacks:"Skript-referanser",
swstretchstyle:"Strekkstil",
swstretchhalign:"Strekk H-justering",
swstretchvalign:"Strekk V-justering",
sound:"Lyd",
progress:"Framdrift",
qtsrc:"QT Src",
qt_stream_warn:"Streamede rtsp-ressurser bør legges til QT Src field i avansert-fanen.Å bør også legge til en ikke-streamet versjon i src field",
align_top:"Topp",
align_right:"Høyre",
align_bottom:"Bunn",
align_left:"Venstre",
align_center:"Midt",
align_top_left:"Topp venstre",
align_top_right:"Topp høyre",
align_bottom_left:"Bunn venstre",
align_bottom_right:"Bunn høyre",
flv_options:"Flash video-valg",
flv_scalemode:"Skalering",
flv_buffer:"Buffer",
flv_startimage:"Startbilde",
flv_starttime:"Starttid",
flv_defaultvolume:"Standardvolum",
flv_hiddengui:"Skjult GUI",
flv_autostart:"Auto-start",
flv_loop:"Løkke",
flv_showscalemodes:"Vis skalering",
flv_smoothvideo:"Jevn video",
flv_jscallback:"JS Callback"
});