tinyMCE.addI18n('nb.advanced',{
style_select:"Stiler",
font_size:"Skriftstørrelse",
fontdefault:"Skriftfamilie",
block:"Format",
paragraph:"Avsnitt",
div:"Div",
address:"Adresse",
pre:"Pre-formatert",
h1:"Overskrift 1",
h2:"Overskrift 2",
h3:"Overskrift 3",
h4:"Overskrift 4",
h5:"Overskrift 5",
h6:"Overskrift 6",
blockquote:"Innrykkinnrykk",
code:"Kode",
samp:"Kodeeksempel",
dt:"Definisjonsuttrykk",
dd:"Definisjonsbeskrivelse",
bold_desc:"Fet",
italic_desc:"Kursiv",
underline_desc:"Understreking",
striketrough_desc:"Gjennomstreking",
justifyleft_desc:"Venstrejuster",
justifycenter_desc:"Midtstill",
justifyright_desc:"Høyrejuster",
justifyfull_desc:"Blokkjuster",
bullist_desc:"Punktliste",
numlist_desc:"Nummerliste",
outdent_desc:"Reduser innrykk",
indent_desc:"øk innrykk",
undo_desc:"Angre",
redo_desc:"Gjør om",
link_desc:"Sett inn / endre lenke",
unlink_desc:"Fjern lenke",
image_desc:"Sett inn / endre bilde",
cleanup_desc:"Rens ukurant kode",
code_desc:"Redigere HTML-koden",
sub_desc:"Senket skrift",
sup_desc:"Hevet skrift",
hr_desc:"Sett inn horisontal linje",
removeformat_desc:"Fjern formatering",
custom1_desc:"Beskrivelse av spesialfunksjon",
forecolor_desc:"Velg skriftfarge",
backcolor_desc:"Velg bakgrunnsfarge",
charmap_desc:"Sett inn spesialtegn",
visualaid_desc:"Slå av/på usynlige elementer",
anchor_desc:"Sett inn / endre anker",
cut_desc:"Klipp ut",
copy_desc:"Kopier",
paste_desc:"Lim inn",
image_props_desc:"Bildeegenskaper",
newdocument_desc:"Nytt dokument",
help_desc:"Hjelp",
blockquote_desc:"Innrykk",
clipboard_msg:"Klipp ut / Kopier /Lim inn fungerer ikke i Mozilla og Firefox. \r\n  Vil du vite mer om dette?",
path:"Sti",
newdocument:"Er du sikker på at du vil slette alt innhold?",
toolbar_focus:"Skift til verktøyknapper - Alt+Q, Skift til editor - Alt-Z, Skift til elementsti - Alt-",
more_colors:"Flere farger"
});