tinyMCE.addI18n('nb.table_dlg',{
general_tab:"Generelt",
advanced_tab:"Avansert",
general_props:"Generelt",
advanced_props:"Generelle egenskaper",
rowtype:"Rad i tabell",
title:"Sett inn / rediger tabell",
width:"Bredde",
height:"Høyde",
cols:"Kolonner",
rows:"Rader",
cellspacing:"Celleavstand",
cellpadding:"Cellefylling",
border:"Ramme",
align:"Justering",
align_default:"Standard",
align_left:"Venstre",
align_right:"Høyre",
align_middle:"Midtstilt",
row_title:"Radegenskaper",
cell_title:"Celleegenskaper",
cell_type:"Celletype",
valign:"Vertikal justering",
align_top:"Topp",
align_bottom:"Bunn",
bordercolor:"Rammefarge",
bgcolor:"Bakgrunn",
merge_cells_title:"Slå sammen celler",
id:"Id",
style:"Stil",
langdir:"Skriftretning",
langcode:"Språkkode",
mime:"Målets MIME-type",
ltr:"Venstre mot høyre",
rtl:"Høyre  mot venstre",
bgimage:"Bakgrunnsbilde",
summary:"Sammendrag",
td:"Data",
th:"Overskrift",
cell_cell:"Oppdater aktuell celle",
cell_row:"Oppdater alle celler i raden",
cell_all:"Oppdater alle celler i tabellen",
row_row:"Oppdater aktuell rad",
row_odd:"Oppdater oddetallsrader",
row_even:"Oppdater partallsrader",
row_all:"Oppdater alle rader",
thead:"Tabellhode",
tbody:"Tabellkropp",
tfoot:"Tabellfot",
scope:"Område",
rowgroup:"Radgruppe",
colgroup:"Kolonnegruppe",
col_limit:"Du har overskredet maksimalt antall kolonner på {$cols}.",
row_limit:"Du har overskredet maksimalt antall rader på {$rows}.",
cell_limit:"Du har overskredet maksimalt antall celler på {$cells}.",
missing_scope:"Er du sikker på at du vil fortsette uten å angi et område for denne overskrifscellen? Uten dette kan det bli vanskelig for enkelte funksjonshemmede brukere å forstå innholdet eller dataene som blir presentert i tabellen.",
caption:"Tabelloverskrift",
frame:"Ramme",
frame_none:"ingen",
frame_groups:"grupper",
frame_rows:"rader",
frame_cols:"kolonner",
frame_all:"alle",
rules:"Streker",
rules_void:"ingen",
rules_above:"over",
rules_below:"under",
rules_hsides:"hsider",
rules_lhs:"lhs",
rules_rhs:"rhs",
rules_vsides:"vsides",
rules_box:"boks",
rules_border:"ramme"
});