tinyMCE.addI18n('nb.advimage_dlg',{
tab_general:"Generelt",
tab_appearance:"Utseende",
tab_advanced:"Avansert",
general:"Generelt",
title:"Tittel",
preview:"Forhåndsvisning",
constrain_proportions:"Behold størrelsesforhold",
langdir:"Skriftretning",
langcode:"Språkkode",
long_desc:"Lang beskrivelse",
style:"Stil",
classes:"Klasser",
ltr:"Venstre mot høyre",
rtl:"Høyre  mot venstre",
id:"Id",
map:"Bildekart",
swap_image:"Bytt bilde",
alt_image:"Alternativt bilde",
mouseover:"for musepeker på",
mouseout:"for musepeker utenfor",
misc:"Annet",
example_img:"Utseende Forhåndsvisning bilde",
missing_alt:"Er du sikker på at du vil fortsette uten å sette inn en beskrivelse av bildet? Uten beskrivelse vil bildet ikke gi mening for enkelte funksjonshemmede eller for personer som bruker en nettleser med bildevisning avslått.",
dialog_title:"Sett inn / endre bilde",
src:"Bildets URL",
alt:"Bildebeskrivelse",
list:"Bildeliste",
border:"Ramme",
dimensions:"Dimensjoner",
vspace:"Vertikal avstand",
hspace:"Horisontal avstand",
align:"Justering",
align_baseline:"Grunnlinje",
align_top:"Topp",
align_middle:"Midtstilt",
align_bottom:"Bunn",
align_texttop:"Tekst topp",
align_textbottom:"Tekst bunn",
align_left:"Venstre",
align_right:"Høyre",
image_list:"Bildeliste"
});