tinyMCE.addI18n('nb.advlink_dlg',{
title:"Sett inn / rediger lenke",
url:"Lenkens URL",
target:"Mål",
titlefield:"Tittel",
is_email:"URL'en du oppga synes å være en email adresse, ønsker du å legge til den nødvendige mailto: prefix?",
is_external:"URL'en du oppga synes å være en ekstern lenke, ønsker du å legge til den nødvendige http:// prefix?",
list:"Lenkeliste",
general_tab:"Generelt",
popup_tab:"Popup",
events_tab:"Hendelser",
advanced_tab:"Avansert",
general_props:"Generelle egenskaper",
popup_props:"Popup-egenskaper",
event_props:"Hendelser",
advanced_props:"Generelle egenskaper",
popup_opts:"Innstillinger",
anchor_names:"Anker",
target_same:"åpne i samme vindu/ramme",
target_parent:"åpne i overordnet vindu/ramme",
target_top:"åpne i toppvindu (erstatter alle rammer)",
target_blank:"åpne i nytt vindu",
popup:"Javascript-popup",
popup_url:"Popup URL",
popup_name:"Vindunavn",
popup_return:"Sett inn \'return false\'",
popup_scrollbars:"Vis rullefelt",
popup_statusbar:"Vis statuslinje",
popup_toolbar:"Vis verktøylinjer",
popup_menubar:"Vis menylinje",
popup_location:"Vis plasseringslinje",
popup_resizable:"Gjør vinduet skalerbart",
popup_dependent:"Avhengig vindu (bare i Mozilla/Firefox)",
popup_size:"Størrelse",
popup_position:"Posisjon (X/Y)",
id:"Id",
style:"Stil",
classes:"Klasser",
target_name:"Målnavn",
langdir:"Skriftretning",
target_langcode:"Målspråk",
langcode:"Språkkode",
encoding:"Tegnkonvertering",
mime:"Målets MIME-type",
rel:"Sidens forhold til målet",
rev:"Målets forhold til siden",
tabindex:"Tabulatorindeks",
accesskey:"Hurtigtast",
ltr:"Venstre mot høyre",
rtl:"Høyre  mot venstre",
link_list:"Lenkeliste"
});