tinyMCE.addI18n('nb.fullpage_dlg',{
title:"Dokumentegenskaper",
meta_tab:"Generelt",
appearance_tab:"Utseende",
advanced_tab:"Avansert",
meta_props:"Metainformasjon",
langprops:"Språk og koding",
meta_title:"Tittel",
meta_keywords:"Nøkkelord",
meta_description:"Beskrivelse",
meta_robots:"Roboter",
doctypes:"Doctype",
langcode:"Språkkode",
langdir:"Skriftretning",
ltr:"Venstre mot høyre",
rtl:"Høyre mot venstre",
xml_pi:"XML-deklarasjon",
encoding:"Tegnkonvertering",
appearance_bgprops:"Bakgrunnsegenskaper",
appearance_marginprops:"Body-marg",
appearance_linkprops:"Lenkefarger",
appearance_textprops:"Tekstegenskaper",
bgcolor:"Bakgrunn",
bgimage:"Bakgrunnsbilde",
left_margin:"Venstre marg",
right_margin:"Høyre marg",
top_margin:"Toppmarg",
bottom_margin:"Bunnmarg",
text_color:"Farge",
font_size:"Skriftstørrelse",
font_face:"Skrifttype",
link_color:"Lenkefarge",
hover_color:"Mus over-farge",
visited_color:"Besøkt-farge",
active_color:"Aktive farge",
textcolor:"Farge",
fontsize:"Skriftstørrelse",
fontface:"Skrifttype",
meta_index_follow:"Indekser, og følg lenkene",
meta_index_nofollow:"Indekser, men ikke følg lenkene",
meta_noindex_follow:"Ikke indekser, men følg lenkene",
meta_noindex_nofollow:"Ikke indekser, og ikke følg lenkene",
appearance_style:"Stilark og stilegenskaper",
stylesheet:"Stilark",
style:"Stil",
author:"Forfatter",
copyright:"Copyright",
add:"Legg til nytt element",
remove:"Fjern",
moveup:"Flytt markert element opp",
movedown:"Flytt markert element ned",
head_elements:"Overskriftselementer",
info:"Informasjon",
add_title:"Tittelelement",
add_meta:"Metaelement",
add_script:"Skriptelement",
add_style:"Stilelement",
add_link:"Lenkeelement",
add_base:"Basiselement",
add_comment:"Kommentarnode",
title_element:"Tittelelement",
script_element:"Skriptelement",
style_element:"Stilelement",
base_element:"Basiselement",
link_element:"Lenkeelement",
meta_element:"Metaelement",
comment_element:"Kommentar",
src:"Skjerm",
language:"Språk",
href:"Href",
target:"Mål",
type:"Type",
charset:"Tegnsett",
defer:"Defer",
media:"Objekt",
properties:"Egenskaper",
name:"Navn",
value:"Verdi",
content:"Innhold",
rel:"Sidens forhold til målet",
rev:"Målets forhold til siden",
hreflang:"Href lang",
general_props:"Generelt",
advanced_props:"Avasert"
});